spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      password: ${REDIS_PASSWORD}
      timeout: 600ms
      host: ${REDIS_HOST}
  cloud:
    openfeign:
      okhttp:
        enabled: true
    function:
      definition: address
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
      bindings:
        address-in-0:
          destination: address-events
          group: user-group
          content-type: application/json

mailgun:
  url: ${MAILGUN_URL}
  key: ${MAILGUN_KEY}

server:
  port: 8081

encrypt:
  key: SONGSONGSOCUTESONGSONGSOCUTESONG
jwt:
  key: Z2lsZG9uZ211LWp3dC1zZWNyZXQta2V5Cg==

logging:
  level:
    org.springframework.cloud.stream: DEBUG