apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-container
          image: 26cm/user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081



  