version: '3.8'

services:
  brand-service:
    build:
      context: .
      dockerfile: ./brand/Dockerfile-test
    ports:
      - "8082:8082"
    environment:
      DB_URL: ${BRAND_DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    networks:
      - ts-network

  user-service:
    build:
      context: .
      dockerfile: ./user/Dockerfile-test
    ports:
      - "8081:8081"
    environment:
      DB_URL: ${USER_DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      MAILGUN_URL: ${MAILGUN_URL}
      MAILGUN_KEY: ${MAILGUN_KEY}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    networks:
      - ts-network

  product-service:
    build:
      context: .
      dockerfile: ./product/Dockerfile-test
    ports:
      - "8083:8083"
    environment:
      DB_URL: ${PRODUCT_DB_URL}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    networks:
      - ts-network

  payment-service:
    build:
      context: .
      dockerfile: ./payment/Dockerfile-test
    ports:
      - "8085:8085"
    environment:
      DB_URL: ${PAYMENT_DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      TOSS_PAYMENT_SECRET: ${TOSS_PAYMENT_SECRET}
    networks:
      - ts-network

  order-service:
    build:
      context: .
      dockerfile: ./order/Dockerfile-test
    ports:
      - "8084:8084"
    environment:
      DB_URL: ${ORDER_DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge

