apiVersion: batch/v1
kind: CronJob
metadata:
  name: order-cancel-job
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: order-cancel
              image: 26cm/order-cancel-job:latest
          restartPolicy: OnFailure