name: API-Documentation

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
      -
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code - ${{github.event.inputs.branch}}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up latest Oracle JDK 22
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 22

      - name: generate jacoco report
        env:
          SPRING_PROFILES_ACTIVE: ci
        run:  |
          chmod +x ./gradlew
          ./gradlew jacocoTestReport --rerun-tasks --no-build-cache

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml

