name: API-Documentation

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Input branch info you want to generate'
        required: true
        default: 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code - ${{github.event.inputs.branch}}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up latest Oracle JDK 22
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 22

      - name: get order API doc
        env:
          SPRING_PROFILES_ACTIVE: ci
        run:  |
          chmod +x ./gradlew 
          ./gradlew :order:clean :order:openapi3

      - name: get brand API doc
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: |
          ./gradlew :brand:clean :brand:openapi3

      - name: get product API doc
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: |
          ./gradlew :product:clean :product:openapi3

      - name: get payment API doc
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: |
          ./gradlew :payment:clean :payment:openapi3

      - name: get user API doc
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: |
          ./gradlew :user:clean :user:openapi3

      - name: prepare api docs yaml files
        run: |
          cp order/build/api-spec/openapi3.yaml ./order.yaml
          cp brand/build/api-spec/openapi3.yaml ./brand.yaml
          cp product/build/api-spec/openapi3.yaml ./product.yaml
          cp payment/build/api-spec/openapi3.yaml ./payment.yaml
          cp user/build/api-spec/openapi3.yaml ./user.yaml

      - name: redoc Join API Docs
        uses: DeltaLaboratory/redocly-cli-action@v1.0.0
        with:
          args: |
            join order.yaml --prefix-tags-with-filename=true brand.yaml --prefix-tags-with-filename=true product.yaml --prefix-tags-with-filename=true payment.yaml --prefix-tags-with-filename=true user.yaml --prefix-tags-with-filename=true --output join.yaml

      - name: redoc Bundle API Docs
        uses: DeltaLaboratory/redocly-cli-action@v1.0.0
        with:
          args: |
            bundle join.yaml --output api-docs.yaml --ext yaml

      - name: update document info
        uses: devorbitus/yq-action-output@v1.1
        with:
          cmd: yq eval -i '.info.title = "twenty-six API DOCS" | .info.description = "Please contact twenty-six backend if there are any issues with API"' api-docs.yaml

      - name: redoc build
        uses: DeltaLaboratory/redocly-cli-action@v1.0.0
        with:
          args: 'build-docs api-docs.yaml --output api-docs.html'

      - name: prepare deployment directory
        run: |
          mkdir -p ./api-docs
          mv api-docs.html ./api-docs/

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-docs
          keep_files: false
          
          
